[package]
name = "automata_playground"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["xtask", "iced_wgpu_rainbow_gain", "baseview_wgpu"]

[dependencies]
bytemuck = "1.15.0"
iced_baseview = {git = "https://github.com/BillyDM/iced_baseview.git"}
